[project]
name = "dags-airflow2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.10.5",
    "apache-airflow-providers-docker>=4.3.1",
    "docker>=7.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
